frameworkVersion: ">=3.21.0 <4.0.0"

service: okdata-pipeline

provider:
  name: aws
  runtime: python3.8
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  timeout: 60
  deploymentBucket:
    name: ${self:custom.deploymentBucket.${self:provider.stage}, self:custom.deploymentBucket.dev}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  logRetentionInDays: 90
  iam:
    role:
      permissionsBoundary: "arn:aws:iam::${aws:accountId}:policy/oslokommune/oslokommune-boundary"
      managedPolicies:
        - 'arn:aws:iam::${aws:accountId}:policy/pipeline_component_policy'
        - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
    VERSION: ${self:custom.version}
  environment:
    AUTHORIZER_API: ${ssm:/dataplatform/shared/api-gateway-url}/simple-dataset-authorizer
    BUCKET_NAME: ok-origo-dataplatform-${self:provider.stage}
    GIT_REV: ${git:branch}:${git:sha1}
    KEYCLOAK_SERVER: ${ssm:/dataplatform/shared/keycloak-server-url}
    SERVICE_NAME: ${self:service}
    STAGE: ${self:provider.stage}
    STATUS_API_URL: ${ssm:/dataplatform/shared/api-gateway-url}/status-api
    VERSION: ${self:custom.version}
    OKDATA_ENVIRONMENT: ${self:custom.okdataEnvironment.${self:provider.stage}, self:custom.okdataEnvironment.dev}
    OKDATA_CLIENT_ID: ${self:service}
    OKDATA_CLIENT_SECRET: ${ssm:/dataplatform/${self:service}/keycloak-client-secret}

package:
  patterns:
    - '!**/*'
    - okdata/**/*.py

functions:
  csv-to-parquet:
    handler: okdata.pipeline.converters.csv.handler.csv_to_parquet
    memorySize: 10240
    timeout: 900
  invoke-lambda:
    handler: okdata.pipeline.lambda_invoker.invoke_lambda
  validate-csv:
    handler: okdata.pipeline.validators.csv.validator.validate_csv
  validate-json:
    handler: okdata.pipeline.validators.json.handler.validate_json
  write-s3:
    handler: okdata.pipeline.writers.s3.handlers.write_s3
    timeout: 900
    tracing: Active
  xls-to-csv:
    handler: okdata.pipeline.converters.xls.main.xls_to_csv
    timeout: 120

plugins:
  - serverless-plugin-git-variables
  - serverless-prune-plugin
  - serverless-python-requirements

resources:
  Description: |
    ${self:service} ${git:branch}:${git:sha1}
    ${git:message}

custom:
  version: 0.1.0
  pythonRequirements:
    dockerizePip: non-linux
    useDownloadCache: false
    useStaticCache: false
    slim: true
    slimPatternsAppendDefaults: false
    slimPatterns:
      - '**/*.py[c|o]'
      - '**/__pycache__*'
      - 'fastparquet/test'
    usePoetry: false
  prune:
    automatic: true
    number: 3
  exportGitVariables: false
  deploymentBucket:
    prod: ok-origo-dataplatform-config-prod
    dev: ok-origo-dataplatform-config-dev
  okdataEnvironment:
    prod: prod
    dev: dev
