frameworkVersion: ">=1.64.0 <2.0.0"

service: okdata-pipeline

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.deploymentBucket.${self:provider.stage}, self:custom.deploymentBucket.dev}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  rolePermissionsBoundary: "arn:aws:iam::#{AWS::AccountId}:policy/oslokommune/oslokommune-boundary"
  iamManagedPolicies:
    - 'arn:aws:iam::#{AWS::AccountId}:policy/pipeline_component_policy'
    - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
    VERSION: ${self:custom.version}
  environment:
    AUTHORIZER_API: ${ssm:/dataplatform/shared/api-gateway-url}/simple-dataset-authorizer
    BUCKET_NAME: ok-origo-dataplatform-${self:provider.stage}
    GIT_REV: ${git:branch}:${git:sha1}
    KEYCLOAK_SERVER: ${ssm:/dataplatform/shared/keycloak-server-url}
    SERVICE_NAME: ${self:service}
    STAGE: ${self:provider.stage}
    STATUS_API_URL: ${ssm:/dataplatform/shared/api-gateway-url}/status-api
    VERSION: ${self:custom.version}
    OKDATA_ENVIRONMENT: ${self:custom.okdataEnvironment.${self:provider.stage}, self:custom.okdataEnvironment.dev}
package:
  exclude:
    - '**/*'
  include:
    - okdata/**/*.py

functions:
  export_csv:
    handler: okdata.pipeline.converters.csv.handler.export
    memorySize: 3008
    timeout: 900
  invoke:
    handler: okdata.pipeline.lambda_invoker.invoke
    iamRoleStatements: []
    iamManagedPolicies:
      - arn:aws:iam::#{AWS::AccountId}:policy/lambda-invoker-policy
  is-latest-edition:
    handler: okdata.pipeline.writers.s3.handlers.is_latest_edition_handler
    timeout: 60
    tracing: Active
    environment:
      CLIENT_ID: s3-writer
      CLIENT_SECRET: ${ssm:/dataplatform/s3-writer/keycloak-client-secret~true}
  validate-csv:
    handler: okdata.pipeline.validators.csv.validator.validate
    timeout: 60
  validate-json:
    handler: okdata.pipeline.validators.json.handler.handle
    timeout: 60
  write-kinesis:
    handler: okdata.pipeline.writers.kinesis.handler.handle
    timeout: 70
    iamRoleStatements: []
    iamManagedPoliciesInherit: true
    iamManagedPolicies:
      - arn:aws:iam::#{AWS::AccountId}:policy/kinesis-writer-policy
    environment:
      CLIENT_ID: kinesis-writer
      CLIENT_SECRET: ${ssm:/dataplatform/kinesis-writer/keycloak-client-secret~true}
  write-s3:
    handler: okdata.pipeline.writers.s3.handlers.copy
    timeout: 900
    tracing: Active
    iamRoleStatements: []
    iamManagedPoliciesInherit: true
    iamManagedPolicies:
      - arn:aws:iam::#{AWS::AccountId}:policy/s3_writer_policy
    environment:
      CLIENT_ID: s3-writer
      CLIENT_SECRET: ${ssm:/dataplatform/s3-writer/keycloak-client-secret~true}
  xls-to-csv:
    handler: okdata.pipeline.converters.xls.main.handler
    timeout: 120

plugins:
  - serverless-es-logs
  - serverless-granular-iam
  - serverless-plugin-git-variables
  - serverless-pseudo-parameters
  - serverless-python-requirements

resources:
  Description: |
    ${self:service} ${git:branch}:${git:sha1}
    ${git:message}

custom:
  version: 0.1.0
  pythonRequirements:
    dockerizePip: non-linux
    useDownloadCache: false
    useStaticCache: false
    slim: true
    slimPatternsAppendDefaults: false
    slimPatterns:
      - '**/*.py[c|o]'
      - '**/__pycache__*'
      - 'fastparquet/test'
    usePoetry: false
  esLogs:
    endpoint: ${ssm:/dataplatform/shared/logs-elasticsearch-endpoint}
    index: dataplatform-services
    filterPattern: '{ $.function_name = "*" }'
  exportGitVariables: false
  deploymentBucket:
    prod: ok-origo-dataplatform-config-prod
    dev: ok-origo-dataplatform-config-dev
  okdataEnvironment:
    prod: prod
    dev: dev
