frameworkVersion: ">=2.10.0 <3.0.0"

service: okdata-pipeline

provider:
  name: aws
  runtime: python3.7
  memorySize: 1024
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.deploymentBucket.${self:provider.stage}, self:custom.deploymentBucket.dev}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  rolePermissionsBoundary: "arn:aws:iam::#{AWS::AccountId}:policy/oslokommune/oslokommune-boundary"
  iamManagedPolicies:
    - 'arn:aws:iam::#{AWS::AccountId}:policy/pipeline_component_policy'
    - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
    - "arn:aws:iam::#{AWS::AccountId}:policy/pipeline_component_policy"
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
    VERSION: ${self:custom.version}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    STAGE: ${self:provider.stage}
    VERSION: ${self:custom.version}
    SERVICE_NAME: ${self:service}
package:
  exclude:
    - '**/*'
  include:
    - okdata/pipeline/**/*.py

functions:
  invoke:
    handler: okdata.pipeline.lambda_invoker.invoke
  validate_csv:
    handler: okdata.pipeline.validators.csv.validator.validate
    timeout: 60
  validate_json:
    handler: okdata.pipeline.validators.json.handler.handle
    timeout: 60
  write_kinesis:
    handler: okdata.pipeline.writers.kinesis.handler.handle
    timeout: 70
  xls_to_csv:
    handler: okdata.pipeline.converters.xls.main.handler
    timeout: 120
    environment:
      BUCKET_NAME: ok-origo-dataplatform-${self:provider.stage}

plugins:
  - serverless-python-requirements
  - serverless-plugin-git-variables
  - serverless-pseudo-parameters
  - serverless-es-logs

resources:
  Description: |
    ${self:service} ${git:branch}:${git:sha1}
    ${git:message}

custom:
  version: 0.1.0
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    usePoetry: false
  esLogs:
    endpoint: ${ssm:/dataplatform/shared/logs-elasticsearch-endpoint}
    index: dataplatform-services
    filterPattern: '{ $.function_name = "*" }'
  exportGitVariables: false
  deploymentBucket:
    prod: ok-origo-dataplatform-config-prod
    dev: ok-origo-dataplatform-config-dev
